# secret 1 is having user details, which doesn't have any permission
# like Select, Insert, Update, Delete in DB
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name1 }}
data:
  username: dXNlcmRhdGFhcHAxCg==      # base64 converted 
  password: VXNlckRhdGFBcHBAMTIzCg==  # base64 converted

---

# secret 2 is having user details, which has permissions granted
# like Select, Insert, Update, Delete in DB
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name2 }}
data:
  username: dXNlcmRhdGFhcHAyCg==      # base64 converted 
  password: VXNlckRhdGFBcHBAMTIzCg==  # base64 converted
