apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.nodeport.name }}
spec:
  type: {{ .Values.service.nodeport.type }}
  ports:
    - port: {{ .Values.service.nodeport.port }}
      targetPort: {{ .Values.service.nodeport.targetport }}
      protocol: TCP
      #nodePort: {{ .Values.service.nodeport.nodePort}}    # Optional: pick a port between 30000-32767
  selector:
    app: {{ .Values.appname }}
    version: "{{ .Chart.AppVersion }}"